### ISSUE TITLE
Does this coin 51 % attack proof

### ISSUE THREAD

**Issue by knkrth** [Nur1Labs/Fruit#1]
Hi, Does this coin 51% attack proof? Because one of your previous developed coin CCM (https://github.com/CatalystCash/Crypto-Coupons-Market) is under 51% attack. 

Are you sure this is 51% attack proof?

**Comment by SoraKohaku** [comment]
yes, this updates more. but I think this old one.

**Comment by knkrth** [comment]
Update to the latest bitcoin version because your customers are  using it & All of them are potential target.

**Comment by SoraKohaku** [comment]
im not used this anymore im used AriA. https://aria.nur1labs.net/

**Comment by ShiroYutha** [comment]
this old code why post this? @FndNur1Labs you post useless again. better remove this repos~

**Comment by SoraKohaku** [comment]
this https://github.com/Nur1Labs/recycle/issues/1
